# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('part_no',)},
        ),
        migrations.AddField(
            model_name='item',
            name='part_no',
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
