# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170129_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Item'),
        ),
    ]
