# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170128_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date_filed',
            field=models.DateField(auto_now_add=True),
        ),
    ]
