# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_item_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='part_no',
            field=models.CharField(max_length=100),
        ),
    ]
