# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='api.Tag'),
        ),
    ]
