# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170128_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Approved', 'Approved'), ('Complete', 'Complete')], default='Waiting', max_length=10),
        ),
    ]
