# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_item_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('model_no',)},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='part_no',
            new_name='model_no',
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
