"""
Django settings for kipventory project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3*4v%9@r16tm(^i$6v%g776at)-&el=a#gnq8zyxezw3ufwd!3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

LOGIN_URL = "/"
LOGIN_REDIRECT_URL = "/app/"
LOGOUT_REDIRECT_URL = "/"

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = "/media/"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # third party
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_swagger',
    'dbbackup',
    'django_cron',
    # local
    'api',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kipventory.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kipventory.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Setting for DJango-DBBackup
# DBBACKUP_STORAGE = 'storages.backends.ftp.FTPStorage'
# DBBACKUP_STORAGE_OPTIONS = {
#     'location': 'ftp://bitnami:submenCo1e@colab-sbx-309.oit.duke.edu:21' #21 is an arbitrary port
# }
DBBACKUP_STORAGE = 'storages.backends.sftpstorage.SFTPStorage'
#DBBACKUP_STORAGE_OPTIONS = {
 #   'host': 'colab-sbx-309.oit.duke.edu',
  #  'params': {
        # 'hostname': '___hostname___',
   #     'username': 'bitnami',
   #     'password': 'submenCo1e',
   # },
   # 'known_host_file': './home/bitnami/.ssh/known_hosts',
   # 'root_path': './',
#}
# DBBACKUP_STORAGE_OPTIONS = {'host': 'https://colab-sbx-309.oit.duke.edu:21'}
SFTP_STORAGE_HOST = 'colab-sbx-309.oit.duke.edu'
SFTP_STORAGE_ROOT = '/home/bitnami'
SFTP_STORAGE_PARAMS = {
    'username': 'bitnami',
    'password': 'submenCo1e',
#    'allow_agent': False,
#    'look_for_keys': False,
}
#SFTP_KNOWN_HOST_FILE = './home/bitnami/.ssh/known_hosts'
#SFTP_STORAGE_INTERACTIVE = False




# Classes working Django-Cron
CRON_CLASSES = [
    "kipventory.crons.Backup",
    # ...
]


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [

]

REST_FRAMEWORK = {
    # 'DEFAULT_PERMISSION_CLASSES': (
    #     'rest_framework.permissions.IsAuthenticated',
    # ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    #'DEFAULT_PAGINATION_CLASS': 'kipventory.api.views.CustomPagination',
    'PAGE_SIZE': 100,
}


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

STATIC_ROOT = os.path.join(BASE_DIR, 'build')

# Email
EMAIL_HOST = "smtp.gmail.com"

EMAIL_HOST_USER = "kipventory@gmail.com"

EMAIL_HOST_PASSWORD = "ece458kipventory"

EMAIL_PORT = 465 #587 for TLS

EMAIL_USE_SSL = True

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

SERVER_EMAIL = EMAIL_HOST_USER
